<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pcmmm" nsURI="pcmmm" nsPrefix="pcmmm">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProduct" abstract="true" eSuperTypes="#//VariabilityConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verbatim" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowspan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colspan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeature" abstract="true" eSuperTypes="#//VariabilityConcept"/>
  <eClassifiers xsi:type="ecore:EClass" name="PCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrix" upperBound="-1"
        eType="#//Matrix" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductFamily" eSuperTypes="#//AbstractProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//AbstractProduct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//AbstractProduct"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureFamily" eSuperTypes="#//AbstractFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//AbstractFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//AbstractFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductComparisonPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="perspectives" upperBound="-1"
        eType="#//PCM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" upperBound="-1"
        eType="#//VariabilityConcept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainCollection" eType="#//DomainCollection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityConcept" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ValuedCell" eOpposite="#//ValuedCell/concepts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//VariabilityConcept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extra" eSuperTypes="#//AbsValuedCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true">
    <eOperations name="eval"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Partial" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Simple" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//VariabilityConcept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiple" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraints" lowerBound="2"
        upperBound="-1" eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unknwon" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inconsistent" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedCell" eSuperTypes="#//AbsValuedCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interpretation" lowerBound="1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" upperBound="-1"
        eType="#//VariabilityConcept" eOpposite="#//VariabilityConcept/constraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOr" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbsValuedCell" abstract="true" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myHeaderProduct" lowerBound="1"
        eType="#//AbstractProduct"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myHeaderFeature" lowerBound="1"
        eType="#//AbstractFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervals" upperBound="-1"
        eType="#//Interval" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainLitteral" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainType" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedDomain" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//OrderedDomain" eOpposite="#//OrderedDomain/next"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//OrderedDomain"
        eOpposite="#//OrderedDomain/previous"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YesNO">
    <eOperations name="eval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
