<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pcmmm" nsURI="pcmmm" nsPrefix="pcmmm">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProduct" abstract="true" eSuperTypes="#//VariabilityConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myValuedCells" upperBound="-1"
        eType="#//ValuedCell" eOpposite="#//ValuedCell/myHeaderProducts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verbatim" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowspan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colspan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeature" abstract="true" eSuperTypes="#//VariabilityConcept">
    <eStructuralFeatures xsi:type="ecore:EReference" name="myValuedCells" upperBound="-1"
        eType="#//ValuedCell" eOpposite="#//ValuedCell/myHeaderFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrices" upperBound="-1"
        eType="#//Matrix" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" upperBound="-1"
        eType="#//VariabilityConcept" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainCollection" lowerBound="1"
        eType="#//DomainCollection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matrix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductFamily" eSuperTypes="#//AbstractProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//AbstractProduct" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//AbstractProduct"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureFamily" eSuperTypes="#//AbstractFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" lowerBound="1"
        upperBound="-1" eType="#//AbstractFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//AbstractFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" lowerBound="1"
        eType="#//Domain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariabilityConcept" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//ValuedCell" eOpposite="#//ValuedCell/concepts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//VariabilityConcept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extra" eSuperTypes="#//Cell"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confident" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partial" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argument" lowerBound="1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Simple" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//VariabilityConcept"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiple" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unknown" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inconsistent" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValuedCell" eSuperTypes="#//Cell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interpretation" eType="#//Constraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concepts" upperBound="-1"
        eType="#//VariabilityConcept" eOpposite="#//VariabilityConcept/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myHeaderProducts" lowerBound="1"
        upperBound="-1" eType="#//AbstractProduct" eOpposite="#//AbstractProduct/myValuedCells"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myHeaderFeatures" lowerBound="1"
        upperBound="-1" eType="#//AbstractFeature" eOpposite="#//AbstractFeature/myValuedCells"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="XOr" eSuperTypes="#//Multiple"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainType" lowerBound="1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interval" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domains" upperBound="-1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Type"/>
  </eClassifiers>
</ecore:EPackage>
